import type { Culture, Ritual } from "../db/schema";
import { v4 as uuid } from "uuid";

// Christian Wedding Rituals
export const christianRituals: Ritual[] = [
  {
    id: uuid(),
    name: "Engagement Ceremony",
    localName: "Engagement",
    description:
      "Formal announcement of the couple's intention to marry, often with exchange of rings at church.",
    significance: "Public declaration of commitment to marry.",
    typicalDuration: 60,
    typicalDay: -90,
    requiredItems: ["Rings", "Bible", "Flowers"],
    participants: ["Bride", "Groom", "Priest/Pastor", "Both families"],
    order: 1,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Bridal Shower",
    localName: "Bridal Shower",
    description:
      "A party for the bride hosted by bridesmaids with gifts and games.",
    significance: "Celebration and gifting before the wedding.",
    typicalDuration: 180,
    typicalDay: -14,
    requiredItems: ["Decorations", "Games", "Gifts"],
    participants: ["Bride", "Bridesmaids", "Female friends/relatives"],
    order: 2,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Bachelor/Bachelorette Party",
    localName: "Stag/Hen Party",
    description:
      "Final celebration of single life for the bride and groom with their friends.",
    significance: "Farewell to single life.",
    typicalDuration: 300,
    typicalDay: -7,
    requiredItems: ["Party supplies", "Venue"],
    participants: ["Bride/Groom", "Close friends"],
    order: 3,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Rehearsal Dinner",
    localName: "Rehearsal Dinner",
    description:
      "Practice run of the wedding ceremony followed by a dinner for the wedding party.",
    significance: "Preparation for the ceremony and bonding.",
    typicalDuration: 180,
    typicalDay: -1,
    requiredItems: ["Venue", "Dinner arrangements"],
    participants: ["Wedding party", "Immediate family", "Officiant"],
    order: 4,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Processional",
    localName: "Walking Down the Aisle",
    description:
      "The formal entrance including groomsmen, bridesmaids, flower girl, ring bearer, and the bride with her father.",
    significance: "Ceremonial entrance to the wedding.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Music", "Flowers", "Ring pillow"],
    participants: ["Wedding party", "Bride", "Father of bride"],
    order: 5,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Opening Prayer & Scripture",
    localName: "Invocation",
    description:
      "The officiant opens with a prayer and readings from the Bible.",
    significance: "Seeking God's blessing on the union.",
    typicalDuration: 10,
    typicalDay: 0,
    requiredItems: ["Bible"],
    participants: ["Officiant"],
    order: 6,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Declaration of Intent",
    localName: "Declaration of Intent",
    description:
      "The officiant asks if both parties willingly enter into marriage.",
    significance: "Confirming free will and consent.",
    typicalDuration: 5,
    typicalDay: 0,
    requiredItems: [],
    participants: ["Officiant", "Bride", "Groom"],
    order: 7,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Exchange of Vows",
    localName: "Wedding Vows",
    description:
      "Bride and groom exchange personal or traditional vows promising love and commitment.",
    significance: "Promises made before God and witnesses.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Vow cards (if needed)"],
    participants: ["Bride", "Groom", "Officiant"],
    order: 8,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Ring Exchange",
    localName: "Exchange of Rings",
    description:
      "Wedding rings are blessed and exchanged as symbols of eternal love.",
    significance: "Physical symbol of the marriage covenant.",
    typicalDuration: 10,
    typicalDay: 0,
    requiredItems: ["Wedding rings"],
    participants: ["Bride", "Groom", "Ring bearer"],
    order: 9,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Unity Ceremony",
    localName: "Unity Candle/Sand",
    description:
      "Lighting a unity candle or pouring sand together symbolizing two becoming one.",
    significance: "Visual representation of the union.",
    typicalDuration: 10,
    typicalDay: 0,
    requiredItems: ["Unity candle set OR sand ceremony set"],
    participants: ["Bride", "Groom"],
    order: 10,
    isOptional: true,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Pronouncement",
    localName: "Pronouncement of Marriage",
    description:
      "The officiant declares the couple as husband and wife before God and witnesses.",
    significance: "Official declaration of the marriage.",
    typicalDuration: 5,
    typicalDay: 0,
    requiredItems: [],
    participants: ["Officiant", "Couple"],
    order: 11,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "First Kiss",
    localName: "You May Kiss the Bride",
    description:
      "The couple shares their first kiss as husband and wife.",
    significance: "Sealing the marriage with a kiss.",
    typicalDuration: 2,
    typicalDay: 0,
    requiredItems: [],
    participants: ["Bride", "Groom"],
    order: 12,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Recessional",
    localName: "Exit Procession",
    description:
      "The newlywed couple exits followed by the wedding party.",
    significance: "Joyful exit as a married couple.",
    typicalDuration: 10,
    typicalDay: 0,
    requiredItems: ["Music", "Confetti/petals (optional)"],
    participants: ["Couple", "Wedding party"],
    order: 13,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Receiving Line",
    localName: "Receiving Line",
    description:
      "Guests congratulate the newlyweds and families after the ceremony.",
    significance: "Personal greetings and well-wishes.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: [],
    participants: ["Couple", "Parents", "Wedding party", "Guests"],
    order: 14,
    isOptional: true,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Wedding Reception",
    localName: "Reception",
    description:
      "Celebration with dinner, speeches, cake cutting, first dance, and dancing.",
    significance: "Celebration with family and friends.",
    typicalDuration: 300,
    typicalDay: 0,
    requiredItems: [
      "Venue",
      "Catering",
      "Wedding cake",
      "DJ/Band",
      "Decorations",
    ],
    participants: ["Couple", "All guests"],
    order: 15,
    isOptional: true,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "First Dance",
    localName: "First Dance",
    description:
      "The couple's first dance as husband and wife, followed by parent dances.",
    significance: "Romantic moment as newlyweds.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Music", "Dance floor"],
    participants: ["Couple", "Parents"],
    order: 16,
    isOptional: true,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "Cake Cutting",
    localName: "Cake Cutting",
    description:
      "The couple cuts the wedding cake together and feeds each other a piece.",
    significance: "Symbolic sharing and first act of togetherness.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Wedding cake", "Cake knife"],
    participants: ["Couple"],
    order: 17,
    isOptional: true,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "Bouquet & Garter Toss",
    localName: "Bouquet/Garter Toss",
    description:
      "Bride throws bouquet to unmarried women; groom tosses garter to unmarried men.",
    significance: "Fun tradition - catchers are said to marry next.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Bouquet", "Garter"],
    participants: ["Couple", "Unmarried guests"],
    order: 18,
    isOptional: true,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "Send-off",
    localName: "Grand Exit",
    description:
      "Guests line up to send off the couple with sparklers, bubbles, or confetti.",
    significance: "Festive farewell as the couple begins married life.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Sparklers/Bubbles/Confetti", "Getaway vehicle"],
    participants: ["Couple", "Guests"],
    order: 19,
    isOptional: true,
    category: "post-wedding",
  },
];

export const christianCulture: Culture = {
  id: "christian",
  name: "Christian",
  region: "Global",
  religion: "Christianity",
  description:
    "Traditional Christian wedding ceremonies celebrated in churches with religious rituals including exchange of vows, ring ceremony, and blessings. Often followed by a reception celebration.",
  isCustom: false,
  rituals: christianRituals,
  createdAt: new Date(),
  updatedAt: new Date(),
};

