import type { Culture, Ritual } from "../db/schema";
import { v4 as uuid } from "uuid";

// North Indian Hindu Wedding Rituals
export const hinduNorthIndianRituals: Ritual[] = [
  {
    id: uuid(),
    name: "Roka / Tilak",
    localName: "रोका / तिलक",
    description:
      "The formal ceremony where both families agree to the match. Tilak is applied to the groom's forehead.",
    significance: "Official declaration of the engagement.",
    typicalDuration: 90,
    typicalDay: -60,
    requiredItems: ["Tilak", "Sweets", "Gifts", "Coconut", "Dry fruits"],
    participants: ["Both families", "Bride", "Groom"],
    order: 1,
    isOptional: false,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Sagai / Ring Ceremony",
    localName: "सगाई",
    description:
      "Exchange of rings between the bride and groom. Gifts and sweets are exchanged between families.",
    significance: "Formal engagement and promise of marriage.",
    typicalDuration: 120,
    typicalDay: -30,
    requiredItems: ["Rings", "Sweets", "Gifts", "Flowers"],
    participants: ["Bride", "Groom", "Both families"],
    order: 2,
    isOptional: false,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Sangeet",
    localName: "संगीत",
    description:
      "A musical night with songs, dances, and performances from both families. DJ and choreographed dances are common.",
    significance: "Celebration bringing both families together through music.",
    typicalDuration: 300,
    typicalDay: -2,
    requiredItems: ["Music system", "Stage", "Decorations", "Catering"],
    participants: ["Both families", "Friends", "Guests"],
    order: 3,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Mehndi",
    localName: "मेहंदी",
    description:
      "Intricate henna designs are applied on the bride's hands and feet. Other women also get mehndi.",
    significance:
      "Symbol of love and prosperity. The darkness of mehndi symbolizes deep love.",
    typicalDuration: 300,
    typicalDay: -1,
    requiredItems: ["Mehndi cones", "Decorations", "Cushions", "Music"],
    participants: ["Bride", "Female relatives", "Friends"],
    order: 4,
    isOptional: false,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Haldi",
    localName: "हल्दी",
    description:
      "Turmeric paste is applied to both bride and groom at their respective homes for glowing skin.",
    significance:
      "Purification ritual and blessing for a beautiful beginning.",
    typicalDuration: 120,
    typicalDay: -1,
    requiredItems: ["Turmeric paste", "Oil", "Yellow clothes", "Flowers"],
    participants: ["Bride/Groom", "Family members"],
    order: 5,
    isOptional: false,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Baraat",
    localName: "बारात",
    description:
      "Grand procession of the groom to the wedding venue on a decorated horse or car with music and dancing.",
    significance: "Triumphant arrival of the groom's party.",
    typicalDuration: 120,
    typicalDay: 0,
    requiredItems: ["Horse/Car", "Band", "Decorations", "Lights"],
    participants: ["Groom", "Groom's family", "Friends", "Band"],
    order: 6,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Milni",
    localName: "मिलनी",
    description:
      "Formal meeting of counterparts from both families. They exchange garlands and gifts.",
    significance: "Uniting of the two families.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Garlands", "Gifts"],
    participants: ["Male relatives from both sides"],
    order: 7,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Jaimala / Varmala",
    localName: "जयमाला / वरमाला",
    description:
      "Exchange of flower garlands between bride and groom, often made competitive by lifting them.",
    significance: "Acceptance of each other as life partners.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Flower garlands", "Stage"],
    participants: ["Bride", "Groom", "Both families"],
    order: 8,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Kanyadaan",
    localName: "कन्यादान",
    description:
      "The bride's father gives his daughter's hand to the groom. Considered the most sacred act.",
    significance: "The ultimate gift - giving one's daughter.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Kalash", "Coconut", "Flowers", "Puja items"],
    participants: ["Bride", "Groom", "Bride's parents", "Priest"],
    order: 9,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Mangal Pheras",
    localName: "मंगल फेरे",
    description:
      "Four rounds around the sacred fire. Each phera has specific vows for dharma, artha, kama, and moksha.",
    significance: "Sacred vows taken around the holy fire.",
    typicalDuration: 45,
    typicalDay: 0,
    requiredItems: ["Sacred fire", "Ghee", "Puffed rice", "Coconut"],
    participants: ["Bride", "Groom", "Priest"],
    order: 10,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Sindoor & Mangalsutra",
    localName: "सिंदूर & मंगलसूत्र",
    description:
      "Groom applies sindoor (vermillion) to the bride's hair parting and ties the mangalsutra.",
    significance:
      "Symbols of married status and lifelong commitment.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Sindoor", "Mangalsutra"],
    participants: ["Bride", "Groom"],
    order: 11,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Saptapadi",
    localName: "सप्तपदी",
    description:
      "Seven steps together, each representing a vow. The marriage is complete after the seventh step.",
    significance: "Seven vows for a happy married life.",
    typicalDuration: 20,
    typicalDay: 0,
    requiredItems: ["Sacred fire", "Betel leaves"],
    participants: ["Bride", "Groom", "Priest"],
    order: 12,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Vidaai",
    localName: "विदाई",
    description:
      "Emotional farewell of the bride from her parental home. She throws rice over her shoulder.",
    significance: "Blessing her parental home while beginning a new journey.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Rice", "Coconut"],
    participants: ["Bride", "Bride's family"],
    order: 13,
    isOptional: false,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "Griha Pravesh",
    localName: "गृह प्रवेश",
    description:
      "Bride enters her new home, kicks a pot of rice with her right foot.",
    significance: "Bringing prosperity to her new home.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Rice pot", "Kumkum", "Rangoli", "Lamp"],
    participants: ["Bride", "Groom", "Groom's family"],
    order: 14,
    isOptional: false,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "Reception",
    localName: "रिसेप्शन",
    description:
      "Grand party hosted by groom's family to introduce the bride to their extended family and friends.",
    significance: "Social celebration and introduction.",
    typicalDuration: 300,
    typicalDay: 1,
    requiredItems: ["Venue", "Catering", "Decorations", "DJ"],
    participants: ["Couple", "All guests"],
    order: 15,
    isOptional: true,
    category: "post-wedding",
  },
];

export const hinduNorthIndianCulture: Culture = {
  id: "hindu-north-indian",
  name: "North Indian Hindu",
  region: "Punjab, Delhi, Uttar Pradesh, Rajasthan",
  religion: "Hindu",
  description:
    "Vibrant North Indian Hindu wedding ceremonies known for grand baraat processions, colorful sangeet nights, elaborate mehndi designs, and joyous celebrations spanning multiple days.",
  isCustom: false,
  rituals: hinduNorthIndianRituals,
  createdAt: new Date(),
  updatedAt: new Date(),
};

