import type { Culture, Ritual } from "../db/schema";
import { v4 as uuid } from "uuid";

// South Indian Hindu Wedding Rituals (Tamil, Kannada, Malayalam)
export const hinduSouthIndianRituals: Ritual[] = [
  {
    id: uuid(),
    name: "Nalangu",
    localName: "நலங்கு (Tamil)",
    description:
      "A fun pre-wedding ceremony where turmeric paste is applied to both bride and groom. Games and playful activities take place.",
    significance: "Purification and celebration before the wedding.",
    typicalDuration: 120,
    typicalDay: -1,
    requiredItems: ["Turmeric", "Oil", "Sandalwood", "Games items"],
    participants: ["Bride", "Groom", "Family", "Friends"],
    order: 1,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Panda Kaal Muhurtham",
    localName: "பந்தக்கால் முகூர்த்தம்",
    description:
      "Erecting the wedding pandal/mandapam. A ceremonial beginning marking the start of wedding celebrations.",
    significance:
      "Marks the formal beginning of wedding preparations with divine blessings.",
    typicalDuration: 60,
    typicalDay: -3,
    requiredItems: ["Bamboo poles", "Mango leaves", "Coconut", "Flowers"],
    participants: ["Both families", "Priest"],
    order: 2,
    isOptional: false,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Vratham",
    localName: "விரதம்",
    description:
      "Fasting and prayers by both bride and groom at their respective homes. Sacred thread ceremony for the groom.",
    significance: "Spiritual preparation for the sacred union.",
    typicalDuration: 180,
    typicalDay: -1,
    requiredItems: ["Sacred thread", "Puja items", "New clothes"],
    participants: ["Bride/Groom", "Priests", "Family elders"],
    order: 3,
    isOptional: false,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Janavasam / Kashi Yatra",
    localName: "ஜனவாசம் / காசி யாத்திரை",
    description:
      "Groom's procession to the wedding venue. He pretends to leave for Kashi but is convinced to marry.",
    significance: "Traditional welcome of the groom's party.",
    typicalDuration: 60,
    typicalDay: 0,
    requiredItems: ["Umbrella", "Decorated vehicle", "Music"],
    participants: ["Groom", "Bride's family", "Guests"],
    order: 4,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Pada Puja",
    localName: "பாத பூஜை",
    description:
      "Bride's parents wash the groom's feet and perform rituals to welcome him as Vishnu.",
    significance: "Honoring the groom and welcoming him into the family.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Water", "Flowers", "Kumkum", "Sandalwood"],
    participants: ["Groom", "Bride's parents"],
    order: 5,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Oonjal",
    localName: "ஊஞ்சல்",
    description:
      "Bride and groom sit on a decorated swing and are swung gently while songs are sung.",
    significance:
      "Symbolizes the ups and downs of married life that the couple will face together.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Decorated swing", "Flowers", "Lamps"],
    participants: ["Bride", "Groom", "Female relatives"],
    order: 6,
    isOptional: true,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Maalai Maatral",
    localName: "மாலை மாற்றல்",
    description:
      "Exchange of garlands between bride and groom. Often playfully competitive with families lifting them.",
    significance: "Mutual acceptance and equality in marriage.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Flower garlands"],
    participants: ["Bride", "Groom", "Both families"],
    order: 7,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Kanyadaanam",
    localName: "கன்யாதானம்",
    description:
      "The bride's father gives her hand to the groom. Water is poured over their joined hands.",
    significance: "The most sacred moment of giving the daughter in marriage.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Water", "Coconut", "Flowers", "Sacred items"],
    participants: ["Bride", "Groom", "Bride's father", "Priest"],
    order: 8,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Mangalya Dharanam",
    localName: "மங்கள்ய தாரணம்",
    description:
      "Tying of the sacred Thali/Mangalsutra around the bride's neck with three knots.",
    significance: "The binding moment that completes the marriage.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Thali/Mangalsutra", "Turmeric thread"],
    participants: ["Bride", "Groom", "Groom's sister"],
    order: 9,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Saptapadi",
    localName: "ஸப்தபதி",
    description:
      "Seven steps around the sacred fire, each representing a vow.",
    significance: "The seven sacred vows that bind the couple.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Sacred fire", "Rice", "Ghee"],
    participants: ["Bride", "Groom", "Priest"],
    order: 10,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Grihapravesam",
    localName: "க்ருஹப்ரவேசம்",
    description:
      "Bride enters her new home, kicking over a pot of rice at the entrance.",
    significance: "Welcoming prosperity into the new home.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Rice pot", "Kumkum", "Lamp", "Rangoli"],
    participants: ["Bride", "Groom", "Groom's family"],
    order: 11,
    isOptional: false,
    category: "post-wedding",
  },
];

export const hinduSouthIndianCulture: Culture = {
  id: "hindu-south-indian",
  name: "South Indian Hindu",
  region: "Tamil Nadu, Karnataka, Kerala",
  religion: "Hindu",
  description:
    "Traditional South Indian Hindu wedding ceremonies combining Tamil, Kannada, and Malayalam customs. Known for elaborate temple-style decorations, classical music, and meaningful rituals.",
  isCustom: false,
  rituals: hinduSouthIndianRituals,
  createdAt: new Date(),
  updatedAt: new Date(),
};

