import type { Culture, Ritual } from "../db/schema";
import { v4 as uuid } from "uuid";

// Muslim (Nikah) Wedding Rituals
export const muslimRituals: Ritual[] = [
  {
    id: uuid(),
    name: "Istikhara",
    localName: "استخارة",
    description:
      "A special prayer seeking Allah's guidance in making the right decision about the marriage proposal.",
    significance:
      "Seeking divine guidance before making an important life decision.",
    typicalDuration: 30,
    typicalDay: -90,
    requiredItems: ["Prayer mat", "Quran"],
    participants: ["Bride/Groom", "Family elders"],
    order: 1,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Mangni / Engagement",
    localName: "منگنی",
    description:
      "Formal engagement ceremony where rings are exchanged and the wedding date is fixed.",
    significance: "Official announcement of the intention to marry.",
    typicalDuration: 120,
    typicalDay: -60,
    requiredItems: ["Rings", "Sweets", "Gifts", "Fruits"],
    participants: ["Bride", "Groom", "Both families"],
    order: 2,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Imam Zamin",
    localName: "امام ضامن",
    description:
      "A gold or silver coin tied to the bride's arm by her mother, seeking blessings for safety.",
    significance: "Blessing and protection for the bride.",
    typicalDuration: 15,
    typicalDay: -7,
    requiredItems: ["Gold/Silver coin", "Thread"],
    participants: ["Bride", "Bride's mother"],
    order: 3,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Manjha",
    localName: "مانجھا",
    description:
      "Similar to Haldi - turmeric paste is applied to the bride and groom at their respective homes.",
    significance: "Purification and beautification before the wedding.",
    typicalDuration: 90,
    typicalDay: -2,
    requiredItems: ["Turmeric paste", "Oil", "Sandalwood", "Yellow clothes"],
    participants: ["Bride/Groom", "Female relatives"],
    order: 4,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Mehndi",
    localName: "مہندی",
    description:
      "Elaborate henna designs are applied on the bride's hands and feet. A celebration with music.",
    significance: "Beautiful adornment symbolizing joy and love.",
    typicalDuration: 300,
    typicalDay: -1,
    requiredItems: ["Mehndi cones", "Decorations", "Music"],
    participants: ["Bride", "Female relatives", "Friends"],
    order: 5,
    isOptional: false,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Sanchaq",
    localName: "سانچق",
    description:
      "The groom's family sends clothes, jewelry, and gifts for the bride.",
    significance: "Groom's family welcoming the bride with gifts.",
    typicalDuration: 60,
    typicalDay: -1,
    requiredItems: ["Clothes", "Jewelry", "Makeup items", "Accessories"],
    participants: ["Groom's family", "Bride's family"],
    order: 6,
    isOptional: true,
    category: "pre-wedding",
  },
  {
    id: uuid(),
    name: "Baraat",
    localName: "بارات",
    description:
      "The groom's procession to the wedding venue with family, friends, and music.",
    significance: "Joyous arrival of the groom's party.",
    typicalDuration: 90,
    typicalDay: 0,
    requiredItems: ["Decorated vehicle", "Band/Music", "Flowers"],
    participants: ["Groom", "Groom's family", "Friends"],
    order: 7,
    isOptional: true,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Nikah",
    localName: "نکاح",
    description:
      "The Islamic marriage ceremony conducted by a Qazi/Maulvi. The Nikah includes the Ijab (proposal) and Qubool (acceptance), witnessed by two male witnesses.",
    significance:
      "The sacred Islamic contract of marriage with Allah as witness.",
    typicalDuration: 60,
    typicalDay: 0,
    requiredItems: ["Nikahnama (contract)", "Quran", "Prayer items"],
    participants: ["Bride", "Groom", "Qazi/Maulvi", "Witnesses", "Wali (guardian)"],
    order: 8,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Mehr Declaration",
    localName: "مہر",
    description:
      "The mandatory gift (money or valuables) given by the groom to the bride as per Islamic law.",
    significance:
      "Financial security and gift to the bride as her right.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Mehr (money/gold/property as agreed)"],
    participants: ["Groom", "Bride", "Witnesses"],
    order: 9,
    isOptional: false,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Arsi Mushraf / First Look",
    localName: "آرسی مشرف",
    description:
      "The bride and groom see each other's faces in a mirror under a dupatta, marking their first look as husband and wife.",
    significance: "Beautiful moment of seeing each other as spouses.",
    typicalDuration: 15,
    typicalDay: 0,
    requiredItems: ["Mirror", "Dupatta/veil", "Quran"],
    participants: ["Bride", "Groom"],
    order: 10,
    isOptional: true,
    category: "wedding-day",
  },
  {
    id: uuid(),
    name: "Rukhsati",
    localName: "رخصتی",
    description:
      "The emotional farewell when the bride leaves her parental home with her husband.",
    significance:
      "Blessing the bride as she begins her new life journey.",
    typicalDuration: 30,
    typicalDay: 0,
    requiredItems: ["Quran (held over head)", "Flowers"],
    participants: ["Bride", "Bride's family", "Groom"],
    order: 11,
    isOptional: false,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "Walima",
    localName: "ولیمہ",
    description:
      "A feast hosted by the groom's family after the wedding to announce the marriage publicly.",
    significance:
      "Sunnah of Prophet Muhammad (PBUH). Public announcement of marriage.",
    typicalDuration: 240,
    typicalDay: 1,
    requiredItems: ["Venue", "Catering", "Decorations"],
    participants: ["Couple", "Groom's family", "Guests"],
    order: 12,
    isOptional: false,
    category: "post-wedding",
  },
  {
    id: uuid(),
    name: "Chauthi / Chauthia",
    localName: "چوتھی",
    description:
      "On the fourth day, the bride visits her parental home with the groom for the first time after marriage.",
    significance: "First visit to bride's home as a married woman.",
    typicalDuration: 180,
    typicalDay: 4,
    requiredItems: ["Gifts", "Sweets"],
    participants: ["Bride", "Groom", "Bride's family"],
    order: 13,
    isOptional: true,
    category: "post-wedding",
  },
];

export const muslimCulture: Culture = {
  id: "muslim",
  name: "Muslim (Nikah)",
  region: "Global - South Asian traditions",
  religion: "Islam",
  description:
    "Islamic wedding ceremonies (Nikah) following the traditions of Prophet Muhammad (PBUH). Combines religious obligations with cultural celebrations including Mehndi, Nikah, and Walima.",
  isCustom: false,
  rituals: muslimRituals,
  createdAt: new Date(),
  updatedAt: new Date(),
};

